config/routes.rb
Rails.application.routes.draw do
  root 'companies#index'
  resources :areas
  resources :companies do
    resources :employees, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :employees, dependent: :destroy
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company
  belongs_to :area
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :cost)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    @employee = Employee.new
    @areas = Area.pluck(:name, :id)
    @employees = @company.employees
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def create
    @company = Company.find(params[:company_id])
    @employee = @company.employees.build(employee_params)
    flash[:notice] = if @employee.save
      'Employee saved correctly'
    else
      'Employee could not be saved'
    end
    redirect_to @employee.company
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    flash[:notice] = 'Your employee was destroyed!!!'
    redirect_to @employee.company
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :area_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
  def employee_total
    total = Area.all.inject(0) do |acc, ele|
      acc + ele.employees.count
    end
    total
  end

  def cost_total
    total = Area.all.inject(0) do |acc, ele|
      acc + ele.cost
    end
    total
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def employee_area(employee)
    area = Area.find(employee.area_id)
    area.name
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation well">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="well">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :cost, 'Cost per employee per month' %>
    <%= form.number_field :cost %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
</div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area, class: 'btn btn-success' %> |
<%= link_to 'Back', areas_path, class: 'btn btn-primary' %>

app/views/areas/index.html.erb
<h1>Areas</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Employee count</th>
      <th>Monthly cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= link_to area.name, area%></td>
        <td><%= area.employees.count %></td>
        <td><%= area.cost * area.employees.count %></td>
        <td><%= link_to 'Edit', edit_area_path(area), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
    <tr class="well">
      <td class="h2">
        <strong>Total:</strong>
      </td>
      <td class="h2"><%= employee_total %></td>
      <td class="h2"><%= cost_total %></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path, class: 'btn btn-primary' %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path, class: 'btn btn-primary' %>

app/views/areas/show.html.erb
<div class="well">
  <h2>
    <strong>Area Name:</strong>
    <%= @area.name %>
  </h2>
  <h2>
    <strong>Cost per employee (monthly):</strong>
    <%= @area.cost %>
  </h2>

  <%= link_to 'Edit', edit_area_path(@area), class: 'btn btn-warning' %> |
  <%= link_to 'Back', areas_path, class: 'btn btn-primary' %>
</div>

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field well">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company, class: 'btn btn-warning' %> |
<%= link_to 'Back', companies_path, class: 'btn btn-primary' %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Employee count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company %></td>
        <td><%= company.employees.count %></td>
        <td><%= link_to 'Edit', edit_company_path(company), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path, class: 'btn btn-primary' %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path, class: 'btn btn-primary' %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-12 well">
    <h2>
      <strong>Company name:</strong>
      <%= @company.name %>
    </h2>
  </div>
</div>

<div class="row">
  <div class="col-md-9 well">
    <h2>Current company employees</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Area</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @employees.each do |emp| %>
            <tr>
              <td><%= emp.first_name %></td>
              <td><%= emp.last_name %></td>
              <td><%= emp.email %></td>
              <td><%= employee_area(emp) %></td>
              <td><%= link_to 'Delete', company_employee_path(emp.company, emp), method: 'delete', class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Edit', edit_company_path(@company), class: 'btn btn-warning' %> |
      <%= link_to 'Back', companies_path, class: 'btn btn-primary' %>
  </div>
  <div class="col-md-3 well">
    <h2>New Employee</h2>
    <%= form_with model: [@company, @employee], class: 'form-horizontal' do |form| %>

      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: 'form-control' %>

      <%= form.label :last_name %>
      <%= form.text_field :last_name, class: 'form-control' %>

      <%= form.label :email %>
      <%= form.email_field :email, class: 'form-control' %>

      <%= form.label :area_id %>
      <%= form.select :area_id, @areas, class: 'form-control' %>
      <br>
      <br>
      <%= form.submit 'Save Employee', class: 'btn btn-success' %>

    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= new_company_path %>">New company</a></li>
        <li><a href="<%= new_area_path %>">New Area</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommpanyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" integrity="sha384-PmY9l28YgO4JwMKbTvgaS7XNZJ30MK9FAZjjzXtlqyZCqBY6X6bXIkM++IkyinN+" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js" integrity="sha384-vhJnz1OVIdLktyixHY4Uk3OHEwdQqPppqYR8+5mjsauETgLOcEynD9oPHhhz18Nw" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if notice %>
    <div class="well">
      <h4 id="notice"><%= notice %></h4>
    </div>
    <% end %>
    <div class="container">
      <%= yield %>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </div>
  </body>
</html>